---
language: python
python: "2.7"

# Require the standard build environment
sudo: required

# Require Ubuntu 14.04
dist: trusty

# Require Java JDK
jdk:
  - oraclejdk8

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - sudo pip install ansible

  # Check ansible version
  - ansible --version

  # Update apt
  - sudo apt-get update -qq

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run the playbook with ansible-playbook
  - ansible-playbook tests/test.yml -i tests/inventory

  # Check Maven is installed
  - file /usr/local/bin/mvn
  - file /usr/local/bin/mvnDebug
  # Since TravisCI comes with it's own mvn we have to explicitly run
  # the mvn we installed.
  - M2_HOME="/opt/maven/apache-maven-3.3.9" /usr/local/bin/mvn --version

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
