---
- name: load version vars
  with_first_found:
    - ../vars/versions/{{ maven_version }}.yml
    - ../vars/versions/default.yml
  include_vars: "{{ item }}"

- name: assert version vars
  assert:
    that:
      - maven_redis_sha256sum not in (None, "")

- name: create local Ansible data directory
  file:
    state: directory
    mode: '0755'
    dest: "{{ local_ansible_data_path }}"

- name: download Maven
  get_url:
    url: "{{ maven_mirror }}/{{ maven_redis_filename }}"
    dest: "{{ local_ansible_data_path }}/{{ maven_redis_filename }}"
    sha256sum: "{{ maven_redis_sha256sum }}"
    force: false
    use_proxy: true
    validate_certs: true
    mode: '0644'

- name: create Maven installation directory
  become: yes
  file:
    state: directory
    owner: 0
    group: 0
    mode: '0755'
    dest: "{{ maven_install_dir }}"

- name: install Maven
  become: yes
  unarchive:
    src: "{{ local_ansible_data_path }}/{{ maven_redis_filename }}"
    dest: "{{ maven_install_dir }}"
    copy: false
    creates: "{{ maven_install_dir }}/apache-maven-{{ maven_version }}"

- name: install mvn link
  become: yes
  file:
    state: link
    force: true
    src: "{{ maven_install_dir }}/apache-maven-{{ maven_version }}/bin/mvn"
    dest: "/usr/local/bin/mvn"

- name: install mvnDebug link
  become: yes
  file:
    state: link
    force: true
    src: "{{ maven_install_dir }}/apache-maven-{{ maven_version }}/bin/mvnDebug"
    dest: "/usr/local/bin/mvnDebug"

- name: create Ansible facts.d directory
  become: yes
  file:
    state: directory
    dest: /etc/ansible/facts.d
    owner: 0
    group: 0
    mode: '0755'

- name: install Maven facts
  become: yes
  template:
    src: facts.j2
    dest: /etc/ansible/facts.d/maven.fact
    owner: 0
    group: 0
    mode: 0644

- name: re-read facts
  setup:
    filter: ansible_local
